### ISSUE TITLE
review of Emem Ekpo's work 

### ISSUE THREAD

**Issue by Ngufor-emmanuella** [ecekpo/Portfolio#5]
Good job  @ecekpo you are almost there 
![image](https://user-images.githubusercontent.com/98039632/207857876-1dd0b733-4cc6-4af5-bd01-2ea8062f11bf.png)

but please there are a few things you still need to do to make your work perfect!
Changes Required:
-please kindly center your headings as to the original design this will make your work look professional and give a good UI to viewers
-please center your submit button following the sample on figma .building a project exactly the same as the project template will show recruiters that you are highly competent and very skillful paving a higher chance for them to recruit you on their team

**Comment by ecekpo** [comment]
Done
